spring:
  application:
    name: logistics
  Kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: isales-logistic
      auto-offset-reset: earliest

isales:
  config:
    kafka:
      topics:
        invoiced-order: 'isales.invoiced-order'
        sent-order: 'isales.sent-order'

logging:
  file:
    name: logs/logistic.log
  level:
    root: INFO
    org.apache.kafka: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: ERROR
    org.apache.kafka.clients.producer.ProducerConfig: ERROR
    org.apache.kafka.common.utils.AppInfoParser: WARN
    org.springframework.kafka: WARN

server:
  port: 8084
